# Inline configuration
# Level: Project (standalone)

branches:
  - main
  - name: beta
    prerelease: true

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - prepareCmd: |
        # Update pyproject.toml version
        sed -i '' 's/^version = ".*"/version = "${nextRelease.version}"/' pyproject.toml
        # Update __init__.py version
        sed -i '' 's/^__version__ = ".*"/__version__ = "${nextRelease.version}"/' src/gapless_network_data/__init__.py
        # Update CLAUDE.md version reference
        sed -i '' 's/^\*\*Version\*\*: v[0-9]*\.[0-9]*\.[0-9]*/**Version**: v${nextRelease.version}/' CLAUDE.md
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
        - pyproject.toml
        - src/gapless_network_data/__init__.py
        - CLAUDE.md
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/github"
