openapi: 3.1.0
info:
  title: Gapless Mempool Data - Documentation Audit Phase
  version: 0.1.1

  description: |
    Documentation quality and completeness fixes based on 5-agent audit.
    Addresses technical accuracy, completeness, code quality, clarity, and applicability.

    This specification serves as the Single Source of Truth (SSoT) for
    documentation improvements, synced with TodoWrite-managed tasks.

  x-metadata:
    audit_date: 2025-11-03
    implementation_status: pending
    last_updated: 2025-11-03T23:00:00Z
    supersedes: []
    audit_agents:
      - schema-technical-accuracy
      - collector-patterns-completeness
      - code-examples-validation
      - documentation-clarity
      - cross-reference-applicability

  x-slos:
    correctness:
      target: 100%
      measurement: All technical claims verified against live APIs
      validation: Empirical testing with curl, API responses
      failure_mode: Outdated schemas, incorrect formulas, wrong field names

    observability:
      target: 100%
      measurement: All documentation issues tracked with severity, location, fix
      log_format: Markdown audit reports with line numbers
      failure_mode: Undocumented issues, lost findings

    maintainability:
      target: Documentation updates require < 30 minutes
      measurement: Time to apply fixes from audit reports
      documentation: Structured reports with before/after examples
      failure_mode: Unclear fix guidance, missing context

x-audit-findings:
  schema-documentation:
    - issue: Blob calculations outdated (EIP-7691)
      impact: All blob utilization metrics incorrect (150% utilization mathematically impossible)
      severity: critical
      location: docs/llamarpc/schema/QUICK_REFERENCE.md lines 134, 267, 269
      resolution: Update max_blob_gas from 786432 to 1179648 (6→9 blobs)
      status: pending
      effort: 15 minutes
      findings:
        - Max blobs per block: 6 should be 9 (line 267)
        - Max blob gas: 786,432 should be 1,179,648 (line 269)
        - Formula uses wrong baseline (line 134)
        - Missing Pectra upgrade (May 2025) from timeline (line 255)
        - Hex-to-decimal examples mismatch (lines 84, 87)

  collector-patterns-documentation:
    - issue: Poor completeness (54.4% score, 39.6% effective coverage)
      impact: Core gapless-network-data features cannot be implemented
      severity: critical
      location: docs/llamarpc/community/collector-patterns.md
      resolution: Add tradeoffs, document missing patterns, fix incomplete patterns
      status: pending
      effort: 14-20 hours
      findings:
        - Zero tradeoff documentation (1.0% coverage)
        - Automatic Backfill pattern incomplete (30% score)
        - Robust Retry Mechanisms incomplete (30% score)
        - Exponential Backoff incomplete (35% score)
        - Four critical patterns completely missing:
          * 5-Layer Validation Pipeline
          * Gap Detection Algorithm
          * Rate Limiting Pattern
          * DuckDB Validation Storage

  applicability-claims:
    - issue: Inaccurate applicability claims (77% accuracy, 10/13 correct)
      impact: Misleading guidance on Ethereum-to-Bitcoin pattern transfer
      severity: major
      location: docs/llamarpc/community/collector-patterns.md lines 342, 389, 360
      resolution: Fix multi-source claims, resolve contradictions, correct terminology
      status: pending
      effort: 1-2 hours
      findings:
        - Multi-source collection overstated (line 342)
        - Internal contradiction: multi-source vs single API (lines 342 vs 389)
        - Terminology confusion: "on-chain validation" for mempool (line 360)

  documentation-standards:
    - issue: Missing YAML frontmatter and formatting violations
      impact: Version tracking broken, iTerm2 Cmd+click non-functional
      severity: major
      location: Both QUICK_REFERENCE.md and collector-patterns.md
      resolution: Add frontmatter, fix file paths, remove promotional language
      status: pending
      effort: 30 minutes
      findings:
        - Missing YAML frontmatter (version tracking)
        - File paths missing trailing space (lines 292-295)
        - Promotional language: "Enterprise-grade reliability" (2 instances)

  code-examples:
    - issue: Limited self-contained examples
      impact: User experience - only 4/16 examples fully copy-paste-ready
      severity: minor
      location: docs/llamarpc/schema/QUICK_REFERENCE.md
      resolution: Add 1-2 complete examples with imports, sample data, expected output
      status: pending
      effort: 1-2 hours

x-tasks:
  critical_path:
    - id: fix-blob-calculations
      title: Update Ethereum blob calculations for EIP-7691
      description: Fix max blobs (6→9), max gas (786432→1179648), formulas, examples
      status: pending
      priority: P0
      dependencies: []
      acceptance_criteria:
        - Update max_blob_gas = 9 * 131072 (line 134)
        - Update "Max blobs per block: 9" (line 267)
        - Update "Max blob gas: 1,179,648" (line 269)
        - Add Pectra upgrade to timeline (line 255)
        - Fix hex/decimal examples (lines 84, 87)
      estimated_effort: 15 minutes
      file: docs/llamarpc/schema/QUICK_REFERENCE.md

    - id: add-pattern-tradeoffs
      title: Add tradeoffs section to all 24 patterns
      description: Document when NOT to use each pattern, complexity costs, limitations
      status: pending
      priority: P0
      dependencies: []
      acceptance_criteria:
        - Each pattern has "⚠️ Tradeoffs" section
        - Coverage: 1.0% → 100%
        - Include: complexity, storage, latency, when to avoid
      estimated_effort: 4-6 hours
      file: docs/llamarpc/community/collector-patterns.md

    - id: document-missing-patterns
      title: Document 4 critical missing patterns
      description: Add 5-Layer Validation, Gap Detection, Rate Limiting, DuckDB Storage
      status: pending
      priority: P0
      dependencies: []
      acceptance_criteria:
        - 5-Layer Validation Pipeline documented
        - Gap Detection Algorithm documented
        - Rate Limiting Pattern documented
        - DuckDB Validation Storage documented
        - Each with architecture, pros/cons, code examples, applicability
      estimated_effort: 6-8 hours
      file: docs/llamarpc/community/collector-patterns.md

    - id: fix-incomplete-patterns
      title: Fix bottom 3 patterns (30-35% scores)
      description: Complete Automatic Backfill, Robust Retry, Exponential Backoff
      status: pending
      priority: P0
      dependencies: []
      acceptance_criteria:
        - Automatic Backfill: 30% → 80% (add gap detection algorithm, examples, applicability)
        - Robust Retry: 30% → 70% (add implementation details, code examples)
        - Exponential Backoff: 35% → 80% (add algorithm, implementation, examples)
      estimated_effort: 4-6 hours
      file: docs/llamarpc/community/collector-patterns.md

    - id: fix-applicability-claims
      title: Fix inaccurate applicability claims
      description: Correct multi-source, resolve contradictions, fix terminology
      status: pending
      priority: P1
      dependencies: []
      acceptance_criteria:
        - Remove/caveat WebSocket API claim (line 342)
        - Reconcile multi-source vs single API contradiction (lines 342 vs 389)
        - Fix "on-chain validation" terminology for mempool (line 360)
        - Add adaptations section explaining why modifications needed
      estimated_effort: 1-2 hours
      file: docs/llamarpc/community/collector-patterns.md

    - id: add-documentation-standards
      title: Add YAML frontmatter and fix formatting
      description: Version tracking, file paths, remove promotional language
      status: pending
      priority: P1
      dependencies: []
      acceptance_criteria:
        - Add YAML frontmatter to both files (version, last_updated, supersedes)
        - Fix file paths with trailing space (lines 292-295)
        - Remove "Enterprise-grade reliability" (2 instances)
        - Compliance: 62% → 85%
      estimated_effort: 30 minutes
      files:
        - docs/llamarpc/schema/QUICK_REFERENCE.md
        - docs/llamarpc/community/collector-patterns.md

  validation_gates:
    - gate: blob_calculations_verified
      description: Blob utilization < 100% on full blocks
      validation: Test with recent blocks containing 9 blobs
      required_before: v0.1.1 release

    - gate: pattern_completeness_minimum
      description: Collector patterns effective coverage ≥ 65%
      validation: Audit confirms critical patterns documented
      required_before: v0.1.1 release

    - gate: no_promotional_language
      description: Zero instances of promotional terms
      validation: grep for "enhanced", "production-grade", "enterprise-grade"
      required_before: v0.1.1 release

x-release-plan:
  v0.1.1:
    target_date: 2025-11-04
    scope: Documentation Audit Fixes
    deliverables:
      - Blob calculations updated for EIP-7691
      - Collector patterns minimum viable completeness (65%)
      - Documentation standards compliance (85%)
      - Applicability claims corrected
    success_gates:
      - blob_calculations_verified
      - pattern_completeness_minimum
      - no_promotional_language
      - CHANGELOG.md updated
      - Git tag v0.1.1 created
    rollback_criteria:
      - Blob utilization still exceeds 100%
      - Pattern completeness below 65%
      - Promotional language remains
