openapi: 3.1.1
info:
  title: Monitoring Skill Enhancement - Phase 2 Findings
  version: 2.0.0
  description: |
    Empirically validated API patterns for Healthchecks.io and UptimeRobot.
    Documents resolved issues and Pushover integration discoveries.

  x-metadata:
    validated: 2025-11-09
    probe_location: /tmp/probe/

components:
  schemas:
    HealthchecksValidation:
      type: object
      properties:
        check_creation_400_error:
          type: object
          properties:
            status:
              const: resolved
            root_cause:
              const: "All fields optional per official docs - minimal payload works"
            validated_payload:
              type: object
              required: [name, timeout, grace]
              example:
                name: "My Check"
                timeout: 3600
                grace: 600
            http_status:
              const: 201

        ping_variations:
          type: object
          properties:
            success_ping:
              const: "GET ping_url - validated"
            start_ping:
              const: "GET ping_url/start - validated"
            fail_ping:
              const: "GET ping_url/fail - validated"
            post_with_body:
              const: "POST ping_url with log message - validated"

        pushover_integration:
          type: object
          properties:
            kind_code:
              const: "po"
              description: "Abbreviated code, not 'pushover'"
            channel_id:
              const: "ecee4935-7504-4ee7-9a10-0bb2f9060024"
            name:
              const: "Pushover"
            discovery_method:
              const: "GET /api/v3/channels/, filter kind in ['pushover', 'po']"

    UptimeRobotValidation:
      type: object
      properties:
        rate_limiting:
          type: object
          properties:
            free_tier_limit:
              const: 10
              description: "requests per minute"
            empirical_measurement:
              const: 10
              description: "requests before 429 error"
            retry_after_header:
              const: 47
              description: "seconds (empirically observed)"
            rate_limit_headers:
              type: object
              properties:
                X-RateLimit-Remaining:
                  type: string
                  description: "Counts down from 9 to 0"
                X-RateLimit-Limit:
                  const: "10"
                Retry-After:
                  type: string
                  description: "Seconds before retry allowed"

        pushover_integration:
          type: object
          properties:
            type_code:
              const: 9
              description: "Shows as 'Slack' in docs, but user configured Pushover"
            contact_id:
              const: "7898795"
            name:
              const: "Pushover integration #1"
            status:
              const: 2
              description: "active"
            alert_contacts_format:
              const: "7898795_0_0"
              description: "ID_threshold_recurrence"
            discovery_method:
              const: "POST getAlertContacts, search by name containing 'pushover'"

  x-completion-status:
    phase_1_documentation_research:
      status: complete
      completed:
        - Official Healthchecks.io API docs fetched
        - Official UptimeRobot API docs fetched
        - Pushover integration patterns researched

    phase_2_probe_validation:
      status: complete
      completed:
        - Healthchecks.io 400 error resolved (minimal payload)
        - Pushover kind code discovered ("po")
        - UptimeRobot rate limit measured (10 req/min)
        - Pushover type code discovered (9)
        - All probe scripts validated

    phase_3_api_client_updates:
      status: complete
      completed:
        - scripts/healthchecks_client.py: get_pushover_channel_id() with "po" check
        - scripts/uptimerobot_client.py: get_pushover_contact_id() with type=9
        - v2.0.0 released with BREAKING CHANGE

    phase_4_documentation_sync:
      status: incomplete
      problem: "Skill documentation out of sync with API client code"
      impact: "Users following SKILL.md examples will get errors (method not found)"
      remaining:
        - Update SKILL.md description (remove "Telegram integration")
        - Replace all Telegram examples with Pushover in SKILL.md
        - Update references/healthchecks-patterns.md (Telegram → Pushover)
        - Update references/uptimerobot-patterns.md (Telegram → Pushover)
        - Add troubleshooting section for 400 errors
        - Document rate limit (10 req/min, not ~6)
        - Add official API docs to references/official-*
        - Document web UI requirement for Pushover setup

  x-deferred-work:
    phase_5_capability_matrices:
      description: "Systematic validation of all documented endpoints"
      reason: "Deferred per user Option B - focus on Pushover integration first"
      endpoints_to_test:
        healthchecks:
          - GET /api/v3/checks/<uuid>
          - POST /api/v3/checks/<uuid>/pause
          - POST /api/v3/checks/<uuid>/resume
          - GET /api/v3/checks/<uuid>/pings
          - GET /api/v3/checks/<uuid>/flips
          - GET /api/v3/badges
        uptimerobot:
          - POST getMonitors (with filters)
          - POST editMonitor
          - POST getMWindows
          - POST newMWindow
          - POST deleteMWindow

  x-key-discoveries:
    healthchecks_api:
      - "kind code for Pushover is 'po' (abbreviated)"
      - "All check creation fields are optional"
      - "Minimal payload: name, timeout, grace"
      - "All ping variations work (success, /start, /fail, POST)"

    uptimerobot_api:
      - "Rate limit is exactly 10 req/min (not ~6 as initially thought)"
      - "Rate limit headers decrement correctly"
      - "Retry-After header provides wait time"
      - "Pushover may use type code 9 (or configured via Slack webhook)"

    integration_patterns:
      - "Both services require web UI configuration for Pushover first"
      - "API can only list and assign existing Pushover integrations"
      - "Cannot create Pushover integrations via API"
