openapi: 3.1.1
info:
  title: Monitoring Skill Enhancement Specification
  version: 2.0.0
  description: |
    Comprehensive validation and enhancement of service-monitoring-setup skill.
    Validates UptimeRobot and Healthchecks.io APIs with Pushover integration.

    **Scope**: API capability validation, Pushover integration, skill refinement
    **Out of Scope**: Telegram integration, custom notification channels

  x-metadata:
    created: 2025-11-09
    updated: 2025-11-09
    status: phase-2-complete
    supersedes: [1.0.0]
    completion:
      phase_1: complete
      phase_2: complete
      phase_3: deferred
      phase_4: partial
      phase_5: deferred

  x-slos:
    availability:
      - Skill loads without errors in Claude Code CLI
      - All bundled scripts execute successfully with uv
      - API clients handle network failures without crashes

    correctness:
      - API patterns validated against official documentation
      - All probe scripts produce expected outputs
      - Check creation/deletion lifecycle completes without errors
      - Pushover integration configuration validated

    observability:
      - Probe scripts log all API requests/responses
      - Validation reports document success/failure for each capability
      - Skill includes troubleshooting guides for common errors

    maintainability:
      - Official documentation excerpts included in references/
      - API version documented (UptimeRobot v2, Healthchecks.io v3)
      - Skill updates versioned with semantic-release

paths:
  /phase-1/fetch-official-documentation:
    get:
      summary: Phase 1 - Fetch Official Documentation
      description: |
        Retrieve and analyze official API documentation for both services.
        Focus on Pushover integration configuration via API.

      x-tasks:
        - task_id: P1T1
          name: Fetch Healthchecks.io API documentation
          implementation:
            - WebFetch https://healthchecks.io/docs/api/
            - Focus: check creation payload, ping URLs, error codes
            - Save: /tmp/probe/healthchecks-io/docs/api-reference.md
          acceptance:
            - Document saved with full API reference
            - Check creation payload format identified
            - Ping URL variations documented

        - task_id: P1T2
          name: Fetch UptimeRobot API documentation
          implementation:
            - WebFetch https://uptimerobot.com/api/
            - Focus: rate limits, monitor types, alert contact types
            - Save: /tmp/probe/uptimerobot/docs/api-reference.md
          acceptance:
            - Document saved with full API reference
            - Rate limit values identified
            - Alert contact types enumerated

        - task_id: P1T3
          name: Research Pushover integration configuration via API
          implementation:
            - WebFetch https://healthchecks.io/docs/api/ (channels section)
            - WebFetch https://uptimerobot.com/api/ (alert contacts section)
            - Search: "pushover" in both documentation sets
            - Determine: Can API create/configure Pushover integrations?
          acceptance:
            - Confirmed whether API can add Pushover integration
            - If yes: Document API endpoint and payload format
            - If no: Document that web UI configuration is required

        - task_id: P1T4
          name: Search community examples and SDKs
          implementation:
            - WebSearch "healthchecks.io api v3 python examples"
            - WebSearch "uptimerobot api python client library"
            - Save relevant examples to /tmp/probe/*/community-examples/
          acceptance:
            - At least 2 community examples found per service
            - Examples demonstrate check/monitor lifecycle

      x-duration: 30 minutes
      x-dependencies: []

  /phase-2/enhanced-probe-validation:
    post:
      summary: Phase 2 - Enhanced Probe Validation
      description: |
        Create and run comprehensive probe scripts that validate all API capabilities.
        Fix 400 errors from initial probes.

      x-tasks:
        - task_id: P2T1
          name: Fix Healthchecks.io check creation (resolve 400 errors)
          implementation:
            - Create: /tmp/probe/healthchecks-io/06_check_lifecycle_corrected.py
            - Use official API documentation payload format
            - Test: create → verify → ping success → ping fail → delete
            - Log all request/response payloads
          acceptance:
            - Check creation succeeds (200 OK)
            - Check appears in list
            - Ping updates check status
            - Deletion succeeds

        - task_id: P2T2
          name: Validate Healthchecks.io ping variations
          implementation:
            - Create: /tmp/probe/healthchecks-io/07_ping_variations.py
            - Test: GET ping_url (success)
            - Test: GET ping_url/fail (failure)
            - Test: GET ping_url/start (job start)
            - Test: POST ping_url with body (log message)
            - Verify status transitions in dashboard
          acceptance:
            - All ping variations succeed
            - Status changes reflected in check
            - Log messages appear in dashboard

        - task_id: P2T3
          name: List and verify Pushover integration (Healthchecks.io)
          implementation:
            - Create: /tmp/probe/healthchecks-io/08_list_pushover_channel.py
            - List all channels with GET /api/v3/channels/
            - Filter: kind == "pushover"
            - Document channel ID for production use
          acceptance:
            - Pushover channel found in list
            - Channel ID documented
            - Channel status verified (active)

        - task_id: P2T4
          name: Measure UptimeRobot rate limits precisely
          implementation:
            - Create: /tmp/probe/uptimerobot/06_rate_limit_measurement.py
            - Make sequential API calls with timing
            - Record: operations before 429 error
            - Record: Retry-After header if present
            - Test: exponential backoff recovery
          acceptance:
            - Exact rate limit documented
            - Retry-After behavior documented
            - Backoff strategy validated

        - task_id: P2T5
          name: List and verify Pushover integration (UptimeRobot)
          implementation:
            - Create: /tmp/probe/uptimerobot/07_list_pushover_contact.py
            - List all alert contacts with getAlertContacts
            - Filter: type == pushover type code
            - Document contact ID and status
          acceptance:
            - Pushover contact found in list
            - Contact ID documented
            - Contact status verified (active)

        - task_id: P2T6
          name: Validate monitor lifecycle with Pushover alerts
          implementation:
            - Create: /tmp/probe/uptimerobot/08_monitor_with_pushover.py
            - Create monitor with Pushover contact ID
            - Verify: monitor created successfully
            - Verify: alert contact associated
            - Delete monitor
          acceptance:
            - Monitor creation with Pushover succeeds
            - Alert association verified
            - Cleanup successful

      x-duration: 60 minutes
      x-dependencies: [P1T1, P1T2, P1T3]

  /phase-3/comprehensive-capability-matrix:
    post:
      summary: Phase 3 - Comprehensive Capability Matrix
      description: |
        Validate every documented API capability systematically.
        Create capability matrix showing what works and what doesn't.

      x-tasks:
        - task_id: P3T1
          name: Create Healthchecks.io capability matrix
          implementation:
            - Test all documented endpoints from API reference
            - Create: /tmp/probe/healthchecks-io/capability-matrix.yaml
            - Format: endpoint, method, tested, status, notes
          acceptance:
            - Matrix covers all documented endpoints
            - Each endpoint has test result
            - Known issues documented

        - task_id: P3T2
          name: Create UptimeRobot capability matrix
          implementation:
            - Test all documented endpoints from API reference
            - Create: /tmp/probe/uptimerobot/capability-matrix.yaml
            - Format: endpoint, parameters, tested, status, notes
          acceptance:
            - Matrix covers all documented endpoints
            - Each endpoint has test result
            - Rate limits per endpoint documented

        - task_id: P3T3
          name: Generate consolidated probe report v2
          implementation:
            - Combine all probe findings
            - Update: /tmp/probe/healthchecks-io/PROBE_REPORT_V2.md
            - Update: /tmp/probe/uptimerobot/PROBE_REPORT_V2.md
            - Include: capability matrix, Pushover config, resolved issues
          acceptance:
            - Reports document all validated capabilities
            - Pushover integration fully documented
            - 400 errors resolved and explained

      x-duration: 30 minutes
      x-dependencies: [P2T1, P2T2, P2T3, P2T4, P2T5, P2T6]

  /phase-4/skill-update-and-refinement:
    put:
      summary: Phase 4 - Skill Update and Refinement
      description: |
        Update skill with validated patterns from official documentation.
        Replace speculative content with confirmed information.

      x-tasks:
        - task_id: P4T1
          name: Update API client scripts with corrections
          implementation:
            - Update: scripts/healthchecks_client.py
            - Fix: check creation payload format
            - Add: validated error handling patterns
            - Update: scripts/uptimerobot_client.py
            - Add: rate limit handling with official values
          acceptance:
            - Scripts use official API patterns
            - All methods have docstrings with examples
            - Error handling covers documented error codes

        - task_id: P4T2
          name: Add official documentation excerpts to references
          implementation:
            - Create: references/official-healthchecks-api.md
            - Create: references/official-uptimerobot-api.md
            - Include: relevant sections from fetched docs
            - Add: source URLs and fetch dates
          acceptance:
            - Official excerpts included verbatim
            - Sources properly attributed
            - Fetch dates documented

        - task_id: P4T3
          name: Update SKILL.md with Pushover integration
          implementation:
            - Replace: "Telegram integration" sections
            - Add: Pushover integration examples
            - Update: Production deployment pattern
            - Add: Troubleshooting for Pushover-specific issues
          acceptance:
            - All examples use Pushover
            - Pushover channel/contact IDs shown
            - Setup instructions reference web UI configuration

        - task_id: P4T4
          name: Add capability matrix to skill resources
          implementation:
            - Copy: capability matrices to references/
            - Add: API coverage summary to SKILL.md
            - Document: validated vs untested capabilities
          acceptance:
            - Capability matrices accessible in skill
            - SKILL.md links to matrices
            - Users can see what's validated

      x-duration: 45 minutes
      x-dependencies: [P3T1, P3T2, P3T3]

  /phase-5/packaging-and-versioning:
    post:
      summary: Phase 5 - Packaging and Versioning
      description: |
        Package updated skill and version with semantic-release.

      x-tasks:
        - task_id: P5T1
          name: Re-package skill with enhancements
          implementation:
            - Run: skill-creator package script
            - Verify: all files included
            - Test: skill loads in Claude Code CLI
          acceptance:
            - Skill package created
            - File size < 100KB
            - Loads without errors

        - task_id: P5T2
          name: Create conventional commit for skill enhancement
          implementation:
            - Git add: .claude/skills/service-monitoring-setup/
            - Git add: specifications/monitoring-skill-enhancement.yaml
            - Commit message: "feat(skills): validate monitoring APIs with Pushover integration"
            - Commit body: Document resolved issues, capability matrices, Pushover config
          acceptance:
            - Commit follows conventional commits format
            - Breaking changes documented if any
            - Scope: skills

        - task_id: P5T3
          name: Version with semantic-release skill
          implementation:
            - Invoke: semantic-release skill
            - Generate: CHANGELOG.md entry
            - Create: git tag for new version
          acceptance:
            - Version bumped correctly
            - CHANGELOG includes all changes
            - Tag created in git

      x-duration: 20 minutes
      x-dependencies: [P4T1, P4T2, P4T3, P4T4]

components:
  schemas:
    CapabilityMatrix:
      type: object
      required:
        - service
        - api_version
        - validated_date
        - capabilities
      properties:
        service:
          type: string
          enum: [healthchecks.io, uptimerobot]
        api_version:
          type: string
          example: "v3"
        validated_date:
          type: string
          format: date
        capabilities:
          type: array
          items:
            type: object
            required:
              - endpoint
              - method
              - tested
              - status
            properties:
              endpoint:
                type: string
                example: "/api/v3/checks/"
              method:
                type: string
                enum: [GET, POST, PUT, DELETE]
              tested:
                type: boolean
              status:
                type: string
                enum: [working, failing, not_tested, deprecated]
              notes:
                type: string
              error_codes:
                type: array
                items:
                  type: integer

x-timeline:
  phase_1: 30 minutes
  phase_2: 60 minutes
  phase_3: 30 minutes
  phase_4: 45 minutes
  phase_5: 20 minutes
  total: 185 minutes (~3 hours)

x-exclusions:
  - Telegram integration (deferred)
  - Custom notification channels
  - Performance optimization
  - Security auditing
  - Multi-account testing
  - Webhook integrations (beyond Pushover)

x-references:
  - Official API Documentation:
      - healthchecks.io: https://healthchecks.io/docs/api/
      - uptimerobot: https://uptimerobot.com/api/
  - Community Resources:
      - Search: "healthchecks.io api v3 python"
      - Search: "uptimerobot api client"
