openapi: 3.1.0
info:
  title: Post-Audit Rectification Specification
  version: 1.0.0
  description: |
    Systematic rectification of issues identified by 6-agent parallel ultra-audit
    of CLAUDE.md updatedness (2025-11-10).

    Audit Findings Summary:
    - Post-Fix Verification: 100% (all Phase 1/2 fixes applied correctly)
    - Specification Alignment: 99% (1 LOW issue - roadmap UptimeRobot lag)
    - Temporal Consistency: 95% (1 CRITICAL - anachronistic date)
    - Dual-Pipeline Reality: 64% (1 HIGH - terminology drift)
    - MotherDuck Section: 95% (1 HIGH - undocumented monitoring)
    - README Alignment: 50% (1 CRITICAL - 3 outdated claims)

    Target: 100% CLAUDE.md accuracy and cross-document consistency
    Estimated Effort: 55 minutes (P0: 20m, P1: 30m, P2: 5m)

  x-metadata:
    project: "gapless-network-data"
    component: "Post-Audit Documentation Rectification"
    created: "2025-11-10"
    last_updated: "2025-11-10"
    status: "planned"
    environment: "documentation"
    supersedes: ["specifications/claude-md-updatedness-phase.yaml"]
    audit_reports:
      - "/tmp/post-fix-verification/VERIFICATION_REPORT.md"
      - "/tmp/specification-alignment/FINAL_ALIGNMENT_REPORT.md"
      - "/tmp/temporal-consistency/AUDIT_SUMMARY.md"
      - "/tmp/dual-pipeline-verification/EXECUTIVE_SUMMARY.md"
      - "/tmp/motherduck-section-audit/EXECUTIVE_SUMMARY.md"
      - "/tmp/readme-claude-alignment/EXECUTIVE_SUMMARY.md"

  x-slos:
    availability:
      target: "Documentation accuracy prevents user confusion and operational errors"
      measurement: "Zero anachronistic dates, zero outdated version claims, zero undocumented systems"
      failure_mode: "Users trust outdated README.md, miss critical monitoring system, confused by dates"
      error_handling: "Raise exception if git operations fail"

    correctness:
      target: "100% temporal consistency and cross-document alignment"
      measurement: |
        - All dates chronologically consistent (no future dates before project start)
        - README.md version matches pyproject.toml and CLAUDE.md
        - All operational infrastructure documented (3/3 Cloud Run Jobs)
        - Terminology consistent (dual-pipeline vs VM-based)
      validation: |
        - grep "2025-01-20" returns no results (anachronism removed)
        - grep "v2.2.1" README.md returns no results (version updated)
        - grep "eth-md-data-quality" CLAUDE.md finds documentation
        - grep "VM-based real-time" CLAUDE.md count reduced by 4
      failure_mode: "Documentation contradicts reality, users cannot trust docs"

    observability:
      target: "All rectification operations tracked with git commits"
      measurement: "Each phase committed separately with conventional commits"
      log_format: "docs(accuracy): <action> - <rationale>"
      failure_mode: "Changes not tracked in version control"

    maintainability:
      target: "<60 minutes for P0+P1+P2 rectification"
      measurement: "Time from start to final commit"
      operations:
        critical_fixes: "20 minutes (P0)"
        documentation_completeness: "30 minutes (P1)"
        specification_sync: "5 minutes (P2)"

  x-phases:
    phase_1_critical_accuracy:
      name: "Fix critical anachronism and README.md outdated claims"
      rationale: "CLAUDE.md has impossible date, README.md severely outdated (50% accuracy)"
      tasks:
        - fix_anachronistic_date
        - update_readme_version
        - update_readme_monitoring
        - update_readme_sdk_status
        - commit_phase_1
      severity: "critical"
      estimated_time: "20 minutes"
      validation:
        - "grep '2025-01-20' CLAUDE.md returns no results"
        - "grep 'v2.4.0' README.md line 11"
        - "grep -v 'UptimeRobot' README.md (except removal notes)"
        - "README.md SDK status clarified as experimental"

    phase_2_documentation_completeness:
      name: "Document missing monitoring system and fix terminology drift"
      rationale: "Data quality checker undocumented, VM-based obscures dual-pipeline"
      tasks:
        - document_data_quality_monitoring
        - fix_vm_based_terminology
        - commit_phase_2
      severity: "high"
      estimated_time: "30 minutes"
      validation:
        - "grep 'eth-md-data-quality' CLAUDE.md finds new section"
        - "grep 'VM-based real-time' CLAUDE.md reduced by 4 occurrences"
        - "All infrastructure components documented (3/3 Cloud Run Jobs)"

    phase_3_specification_sync:
      name: "Update master roadmap UptimeRobot reference"
      rationale: "Roadmap specification lags operational reality"
      tasks:
        - update_roadmap_monitoring
        - commit_phase_3
      severity: "low"
      estimated_time: "5 minutes"
      validation:
        - "grep 'UptimeRobot removed' specifications/master-project-roadmap.yaml"

  x-implementation:
    phase_1_critical_accuracy:
      task_1:
        id: "fix_anachronistic_date"
        intent: "Remove impossible documentation date (9.5 months before project start)"
        file: "CLAUDE.md"
        changes:
          - line: 912
            from: 'last_updated: "2025-01-20"'
            to: 'last_updated: "2025-11-10"'
        rationale: |
          Copy-paste placeholder from documentation standards example that was never updated.
          First commit was 2025-11-03, so 2025-01-20 is temporally impossible.
        validation: "grep -n '2025-01-20' CLAUDE.md returns empty"

      task_2:
        id: "update_readme_version"
        intent: "Sync README.md version with pyproject.toml and CLAUDE.md"
        file: "README.md"
        changes:
          - line: 11
            from: "**Status**: Production operational (v2.2.1)"
            to: "**Status**: Production operational (v2.4.0)"
        rationale: |
          pyproject.toml shows version = "2.4.0", CLAUDE.md shows v2.4.0, git tag is v2.4.0.
          README.md is only document showing outdated v2.2.1.
        validation: "grep 'v2.4.0' README.md"

      task_3:
        id: "update_readme_monitoring"
        intent: "Remove UptimeRobot from active monitoring list"
        file: "README.md"
        changes:
          - line: 41
            action: "Remove 'UptimeRobot: HTTP endpoint monitoring' line"
          - line: 241
            action: "Remove UptimeRobot reference if present"
        rationale: |
          UptimeRobot was removed (commit d3e7271) due to Cloud Run incompatibility.
          CLAUDE.md correctly shows "UptimeRobot removed", README.md still lists as active.
        validation: "grep -i 'uptimerobot' README.md | grep -v -i 'removed'"

      task_4:
        id: "update_readme_sdk_status"
        intent: "Clarify SDK status as experimental code (not purely future work)"
        file: "README.md"
        investigation_required: true
        steps:
          - "Read README.md line 281 SDK status claim"
          - "Verify src/gapless_network_data/api.py exists with fetch_snapshots()"
          - "Update wording to reflect code exists but is experimental/not production"
        rationale: |
          README.md says "Future Work: Python SDK" but api.py exists with implemented functions.
          CLAUDE.md correctly states "implemented (src/gapless_network_data/api.py)".

    phase_2_documentation_completeness:
      task_1:
        id: "document_data_quality_monitoring"
        intent: "Add missing documentation for eth-md-data-quality-checker Cloud Run Job"
        file: "CLAUDE.md"
        section: "MotherDuck Integration"
        location: "After line 224 (Service Management section)"
        content: |
          ### Data Quality Monitoring

          **Cloud Run Job** (data quality checks):

          ```bash
          # View execution history
          gcloud run jobs executions list --job eth-md-data-quality-checker --region us-central1

          # Manual trigger
          gcloud run jobs execute eth-md-data-quality-checker --region us-central1
          ```

          **Monitoring Schedule**: Every 5 minutes via Cloud Scheduler (`eth-md-data-quality`)

          **Purpose**: Queries MotherDuck for latest block timestamp and verifies data freshness (<300s threshold). Exits with code 1 if data is stale, triggering Cloud Run Job failure alerts.

          **Deployment**: `deployment/cloud-run/data_quality_checker.py`
        also_update:
          - section: "Overview"
            action: "Update lines 139-144 to list data quality monitoring as component"
          - section: "Operational Status"
            line: 304
            action: "Add eth-md-data-quality-checker to operational infrastructure list"
        rationale: |
          Cloud Run Job eth-md-data-quality-checker runs every 5 minutes (55 executions verified).
          Completely undocumented in CLAUDE.md despite being critical monitoring infrastructure.
          Operators currently unaware of this monitoring layer.

      task_2:
        id: "fix_vm_based_terminology"
        intent: "Replace VM-based with dual-pipeline to accurately describe architecture"
        file: "CLAUDE.md"
        changes:
          - line: 123
            from: "VM-based real-time ingestion"
            to: "dual-pipeline ingestion"
          - line: 440
            from: "via VM-based real-time streaming"
            to: "via dual-pipeline architecture"
          - line: 490
            from: "VM-based real-time collection"
            to: "dual-pipeline collection"
          - line: 747
            from: "VM-based real-time collection"
            to: "dual-pipeline architecture"
        rationale: |
          Empirical verification confirmed dual-pipeline IS operational (VM + Cloud Run Job).
          "VM-based" terminology obscures BigQuery hourly component existence.
          Creates inconsistency with 7 other locations that correctly say "dual-pipeline".
        validation: "grep -c 'VM-based real-time' CLAUDE.md should be 0"

    phase_3_specification_sync:
      task_1:
        id: "update_roadmap_monitoring"
        intent: "Sync master roadmap monitoring claim with operational reality"
        file: "specifications/master-project-roadmap.yaml"
        changes:
          - line: 38
            from: "Healthchecks.io + UptimeRobot + Pushover (all cloud-based)"
            to: "Healthchecks.io + Pushover (cloud-based, UptimeRobot removed)"
        rationale: |
          CLAUDE.md correctly documents UptimeRobot removal (commit d3e7271).
          Master roadmap specification has documentation lag.
        validation: "grep 'UptimeRobot removed' specifications/master-project-roadmap.yaml"

  x-validation:
    post_phase_1:
      - "CLAUDE.md has no anachronistic dates (all dates >= 2025-11-03)"
      - "README.md version matches pyproject.toml (v2.4.0)"
      - "README.md monitoring matches CLAUDE.md (no UptimeRobot)"
      - "README.md SDK status clarified"

    post_phase_2:
      - "Data quality monitoring system documented in CLAUDE.md"
      - "All 3 Cloud Run Jobs documented (eth-md-updater, eth-md-data-quality-checker, ethereum-historical-backfill)"
      - "VM-based terminology replaced with dual-pipeline (4 locations)"
      - "Architectural terminology consistent throughout"

    post_phase_3:
      - "Master roadmap monitoring matches CLAUDE.md"
      - "All specifications aligned with operational reality"

    final:
      - "Total commits: 3 (one per phase)"
      - "All commits use conventional format (docs(accuracy):)"
      - "semantic-release executed after each phase"
      - "CLAUDE.md accuracy: 95% → 100% (target)"
      - "README.md accuracy: 50% → 100% (target)"
      - "Cross-document consistency: 100%"

paths: {}
components: {}
